apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdk 37
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    defaultConfig {
        applicationId "com.example.zombiechat"
        minSdkVersion 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.example.zombiechat'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.firebase:firebase-firestore:26.6.0'
    implementation 'com.google.firebase:firebase-storage:22.0.2'
    implementation 'androidx.lifecycle:lifecycle-livedata-core:2.11.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.activity:activity:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'


    //for tab layout
    implementation("com.google.android.material:material:1.14.0")

    //google sign in dependencies
    implementation 'com.google.firebase:firebase-auth:24.2.0'
    implementation 'com.google.android.gms:play-services-auth:22.0.0'

    //circular image view
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    // FirebaseUI for Cloud Firestore
    implementation 'com.firebaseui:firebase-ui-firestore:9.1.1'

    //picasso library
    implementation 'com.squareup.picasso:picasso:2.71828'

    //for firebase crashlytics
    implementation 'com.google.firebase:firebase-crashlytics:20.1.1'

    // Check for v11.4.2 or higher
    implementation 'com.google.firebase:firebase-core:21.1.1'

    // credential manager for google signin
    implementation "androidx.credentials:credentials:1.6.0"
    implementation "androidx.credentials:credentials-play-services-auth:1.6.0"
    implementation "com.google.android.libraries.identity.googleid:googleid:1.2.1"

    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.11.0"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.11.0"

    implementation("io.insert-koin:koin-android:4.2.2")
    implementation("io.insert-koin:koin-androidx-compose:4.2.2")




    // for performance monitoring
    implementation(platform("com.google.firebase:firebase-bom:34.19.0"))
    implementation("com.google.firebase:firebase-perf")



}
